### ISSUE TITLE
can't find cypari.h

### ISSUE THREAD

**Issue by beew** [mkauers/ore_algebra#57]
Hi, I am trying to install ore_algebra on sage with
```
sage -i ore_algebra

```

It failed with 

```
INFO: compile options: '-I/home/bernard/opt/sagemath/src/sage/libs/arb -I/home/bernard/opt/sagemath/src/sage/libs/flint -I/home/bernard/opt/sagemath/src/sage/cpython -I/home/bernard/opt/sagemath/src -I/home/bernard/opt/sagemath/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -I/home/bernard/opt/sagemath/local/var/lib/sage/venv-python3.10/include -I/usr/include/python3.10 -c'
      extra options: '-std=c++11'
      INFO: gcc: src/ore_algebra/analytic/binary_splitting_arb.cpp
      src/ore_algebra/analytic/binary_splitting_arb.cpp:799:10: fatal error: cypari.h: No such file or directory
        799 | #include "cypari.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/bernard/opt/sagemath/src/sage/libs/arb -I/home/bernard/opt/sagemath/src/sage/libs/flint -I/home/bernard/opt/sagemath/src/sage/cpython -I/home/bernard/opt/sagemath/src -I/home/bernard/opt/sagemath/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -I/home/bernard/opt/sagemath/local/var/lib/sage/venv-python3.10/include -I/usr/include/python3.10 -c src/ore_algebra/analytic/binary_splitting_arb.cpp -o build/temp.linux-x86_64-cpython-310/src/ore_algebra/analytic/binary_splitting_arb.o -std=c++11" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ore_algebra
  Running setup.py clean for ore_algebra
Failed to build ore_algebra
Installing collected packages: ore_algebra
  Running setup.py install for ore_algebra: started
  Running setup.py install for ore_algebra: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for ore_algebra did not run successfully.
  │ exit code: 1

```
Cypari is already installed in sage and cypari.h is in $SAGE_ROOT/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/cypari2

OS is Ubuntu 22.04.

Thanks.

**Comment by mezzarobba** [comment]
Hi,

Thank you for the report. On which OS are you? How did you install Sage 
(from source, from OS packages, ...)?

-- 
Marc

**Comment by beew** [comment]
OS is Ubuntu 22.04, I installed sage from source.

**Comment by mezzarobba** [comment]
On Thursday, 19 January 2023 14:39:37 CET beew wrote:
> OS is Ubuntu 22.04, I installed sage from source.

Then it's strange that it doesn't work. Which version of Sage do you 
have? What happens if you do

sage -pip install git+https://github.com/mkauers/ore_algebra.git

instead of sage -i?

-- 
Marc

**Comment by beew** [comment]
Hi, 

sage -pip install works. So it couldn't build the wheel but could install the binary,

sage 9.7

**Comment by mezzarobba** [comment]
Ok, I believe I understand what is going on. I opened a ticket on the 
Sage trac server.

https://trac.sagemath.org/ticket/34924

-- 
Marc

**Comment by mezzarobba** [comment]
@beew If by any chance you could check if the branch attached fixes the issue for you, that would be great. (Rebuild Sage after merging in this branch, then run `sage -pip uninstall ore_algebra` and finally `sage -i ore_algebra`).

**Comment by mezzarobba** [comment]
Fixed in Sage.

**Comment by beew** [comment]
Still failed in sage 9.8. I have to change the one line  (the patch) manually for it to work

**Comment by mezzarobba** [comment]
Yes, the fix will be in sage 10.0.
